version: '2.2'
services:
  chatfiles:
    image: chatfiles:latest
    container_name: chatfiles
    ports:
      - 5001:5001
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  chatfiles-ui:
    image: chatfiles-ui:latest
    container_name: chatfiles-ui
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_FILES_SERVER_HOST=http://chatfiles:5001
      - NEXT_PUBLIC_CHAT_FILES_MAX_SIZE=0
    depends_on:
      - chatfiles