# fly.toml file generated for mnc-chatfiles-server on 2023-04-28T14:20:06+09:00

app = "mnc-chatfiles-server"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "hkg"

[[services]]
  protocol = "tcp"
  internal_port = 5001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
